In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

In [2]:
wine = pd.read_csv('https://bit.ly/wine_csv_data')

In [3]:
wine.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [4]:
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()
target = wine['class'].to_numpy()

In [6]:
data[:5]

array([[9.4 , 1.9 , 3.51],
       [9.8 , 2.6 , 3.2 ],
       [9.8 , 2.3 , 3.26],
       [9.8 , 1.9 , 3.16],
       [9.4 , 1.9 , 3.51]])

In [7]:
target[:5]

array([0., 0., 0., 0., 0.])

In [11]:
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [12]:
sub_input, val_input, sub_target, val_target = train_test_split(train_input, train_target, test_size=0.2, random_state=42)

In [13]:
print(sub_input.shape, val_input.shape)

(4157, 3) (1040, 3)


In [16]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)

DecisionTreeClassifier(random_state=42)

In [17]:
print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

0.9971133028626413
0.864423076923077


In [21]:
from sklearn.model_selection import cross_validate

scores = cross_validate(dt, train_input, train_target)
np.mean(scores['test_score'])

0.855300214703487

In [22]:
from sklearn.model_selection import StratifiedKFold

scores2 = cross_validate(dt, train_input, train_target)
np.mean(scores2['test_score'])

0.855300214703487

In [23]:
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
score_10 = cross_validate(dt, train_input, train_target, cv=splitter)
score_10

{'fit_time': array([0.00989604, 0.00659013, 0.00731683, 0.00554895, 0.00614095,
        0.00590396, 0.00622511, 0.00603104, 0.00629091, 0.00677514]),
 'score_time': array([0.00057602, 0.00052881, 0.00055695, 0.00057507, 0.00074601,
        0.00039911, 0.00049376, 0.00050092, 0.00055885, 0.00068402]),
 'test_score': array([0.83461538, 0.87884615, 0.85384615, 0.85384615, 0.84615385,
        0.87307692, 0.85961538, 0.85549133, 0.85163776, 0.86705202])}

In [36]:
from sklearn.model_selection import GridSearchCV

params = {
  'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
  'max_depth': range(5, 20, 1),
  'min_samples_split': range(2, 100, 10)
}
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [26]:
dt = gs.best_estimator_
print(dt.score(train_input, train_target))

0.9615162593804117


In [37]:
gs.best_params_

{'max_depth': 14, 'min_impurity_decrease': 0.0004, 'min_samples_split': 12}

In [28]:
gs.cv_results_

{'mean_fit_time': array([0.00517092, 0.00387354, 0.00420504, 0.0034317 , 0.00326486]),
 'std_fit_time': array([0.00053372, 0.00022057, 0.00042362, 0.00020253, 0.00018091]),
 'mean_score_time': array([0.00059781, 0.00055318, 0.00056553, 0.00046606, 0.00049601]),
 'std_score_time': array([5.08478362e-05, 1.36163971e-04, 1.82492253e-05, 5.49105266e-05,
        1.26825651e-04]),
 'param_min_impurity_decrease': masked_array(data=[0.0001, 0.0002, 0.0003, 0.0004, 0.0005],
              mask=[False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'min_impurity_decrease': 0.0001},
  {'min_impurity_decrease': 0.0002},
  {'min_impurity_decrease': 0.0003},
  {'min_impurity_decrease': 0.0004},
  {'min_impurity_decrease': 0.0005}],
 'split0_test_score': array([0.86923077, 0.87115385, 0.86923077, 0.86923077, 0.86538462]),
 'split1_test_score': array([0.86826923, 0.86346154, 0.85961538, 0.86346154, 0.86923077]),
 'split2_test_score': array([0.8825794 , 0.8

In [42]:
np.max(gs.cv_results_['mean_test_score'])

0.8683865773302731

In [43]:
from scipy.stats import uniform, randint

In [48]:
rgen = randint(0, 10)
rgen.rvs(10)

array([6, 8, 9, 5, 7, 8, 1, 0, 2, 8])

In [52]:
np.unique(rgen.rvs(1000000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 99825,  99986, 100193, 100022,  99829, 100494, 100031,  99607,
        100538,  99475]))

In [55]:
ugen = uniform(0, 1)
ugen.rvs(10)

array([0.00801637, 0.46669417, 0.06064132, 0.12487475, 0.94698591,
       0.26597739, 0.09122788, 0.89339241, 0.60388943, 0.35779362])

In [57]:
from sklearn.model_selection import RandomizedSearchCV

params = {
  'min_impurity_decrease': uniform(0.0001, 0.001),
  'max_depth': randint(20, 50),
  'min_samples_split': randint(2, 25),
  'min_samples_leaf': randint(1, 25)
}

gs2 = RandomizedSearchCV(DecisionTreeClassifier(random_state=42), params, n_iter=100, n_jobs=-1, random_state=42)
gs2.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7ffa6a6125b0>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7ffa6a612400>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7ffa4b639a30>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_frozen object at 0x7ffa4b63e850>},
                   random_state=42)

In [58]:
gs2.best_params_

{'max_depth': 39,
 'min_impurity_decrease': 0.00034102546602601173,
 'min_samples_leaf': 7,
 'min_samples_split': 13}

In [59]:
np.max(gs.cv_results_['mean_test_score'])

0.8683865773302731

In [61]:
dt = gs.best_estimator_
dt.score(test_input, test_target)

0.8615384615384616